window.DECKS = window.DECKS || {};
window.DECKS.character = [

  "A corporate HR manager",
  "A medieval monk",
  "A very serious lawyer",
  "A nervous kindergarten teacher",
  "A professional hitman",
  "A street magician",
  "A retired librarian",
  "A wedding planner under pressure",
  "A conspiracy theorist",
  "A burnt-out startup founder",

  "A small-town mayor",
  "A celebrity personal assistant",
  "A food critic who hates everything",
  "A pacifist philosophy student",
  "A reality TV contestant",
  "A safety inspector",
  "A motivational speaker",
  "A violinist late for rehearsal",
  "A museum tour guide",
  "A social media influencer livestreaming",

  "A night-shift security guard",
  "A disaster preparedness consultant",
  "A substitute teacher on their first day",
  "A high-end real estate agent",
  "A war correspondent",
  "A sleep-deprived medical intern",
  "A tax auditor",
  "A yoga instructor",
  "A customer support representative",
  "A street food vendor",

  "A data analyst obsessed with spreadsheets",
  "A park ranger",
  "A freelance journalist",
  "A professional gambler",
  "A crisis PR consultant",
  "A climate scientist",
  "A museum conservator",
  "A delivery driver running late",
  "A theater stage manager",
  "A city tour guide",

  "A risk-averse insurance adjuster",
  "A wedding guest who doesn’t know anyone",
  "A grant application reviewer",
  "A startup pitch coach",
  "A building maintenance supervisor",
  "A graduate student who regrets everything",
  "A corporate compliance officer",
  "A funeral director",
  "A public relations intern",
  "A very polite bureaucrat"

];