window.DECKS = window.DECKS || {};
window.DECKS.ingredient = [

  "A heavy winter coat with deep pockets",
  "A frayed rope tied in several bad knots",
  "A distracted security guard on a headset",
  "A loose wooden ladder missing one rung",
  "A plastic bucket half full of liquid",
  "A dangling electrical cable",
  "A reinforced fire door with a slow closer",
  "A cracked smartphone buzzing repeatedly",
  "A loud mechanical noise from nearby",
  "A rolled-up carpet",

  "A flickering emergency light",
  "A fire extinguisher with a low pressure gauge",
  "A vending machine that keeps eating coins",
  "A pair of noise-canceling headphones",
  "A locked toolbox with a cracked hinge",
  "A shopping cart with one stuck wheel",
  "A reflective safety vest",
  "A spilled box of office supplies",
  "A coil of industrial plastic wrap",
  "A glass wall with visible stress fractures",

  "A leaking water pipe",
  "A heavy backpack filled with unknown items",
  "A security badge on a retractable cord",
  "A pile of folded chairs",
  "A janitor’s cart with mixed cleaning chemicals",
  "A warning sign that has fallen over",
  "A malfunctioning automatic door",
  "A stack of instruction manuals in the wrong language",
  "A rolling whiteboard covered in diagrams",
  "A surveillance camera slowly rotating",

  "A half-deflated inflatable object",
  "A portable speaker playing at full volume",
  "A loose floor panel",
  "A thick curtain on a ceiling track",
  "A box labeled “FRAGILE” with no other markings",
  "A maintenance hatch slightly ajar",
  "A clipboard with incomplete checklists",
  "A pair of protective gloves two sizes too large",
  "A coiled hose attached to nothing",
  "A wheeled suitcase with a broken handle",

  "A flashing red countdown display with no label",
  "A stack of shipping pallets",
  "A reflective mirror mounted at an odd angle",
  "A heavy doorstop shaped like an animal",
  "A pile of sandbags",
  "A metal railing warm to the touch",
  "A fog machine set to maximum output",
  "A clipboard stamped “APPROVED”",
  "A retractable barrier belt",
  "A laminated evacuation map missing key sections"

];