window.DECKS = window.DECKS || {};
window.DECKS.plotarmor = [

  "It works only because everyone assumes it’s supposed to happen",
  "It works only because a warning label is interpreted backwards",
  "It works only because someone misunderstands a simple gesture",
  "It works only because the villain insists on explaining their plan",
  "It works only because one absurd detail becomes incredibly important",
  "It works only because the floor is weirdly slippery for no reason",
  "It works only because a door that should open doesn’t, and vice versa",
  "It works only because gravity behaves slightly wrong at the worst moment",
  "It works only because the loudest noise masks everything else",
  "It works only because a timer is dramatically inaccurate",

  "It works only because an object survives what it shouldn’t",
  "It works only because something breaks in exactly the helpful way",
  "It works only because the most fragile thing is suddenly durable",
  "It works only because a perfect coincidence happens mid-panic",
  "It works only because a crowd turns into a moving obstacle course",
  "It works only because someone shouts the wrong instructions confidently",
  "It works only because a professional tries to enforce procedure",
  "It works only because a minor inconvenience becomes a major shield",
  "It works only because the environment behaves like a stage set",
  "It works only because the laws of probability take a coffee break",

  "It works only because a small lie becomes a life-saving commitment",
  "It works only because a distraction spirals into chaos",
  "It works only because the camera would cut away at this moment",
  "It works only because the character refuses to acknowledge pain",
  "It works only because one person is weirdly calm and authoritative",
  "It works only because the nearest object is used for the wrong job",
  "It works only because the escape is socially embarrassing",
  "It works only because a romantic gesture accidentally becomes tactical",
  "It works only because someone is trying to impress someone else",
  "It works only because a totally unnecessary backflip happens",

  "It works only because the villain hesitates for dramatic effect",
  "It works only because the character monologues while moving",
  "It works only because a misunderstanding creates a temporary alliance",
  "It works only because a sign is taken as a personal challenge",
  "It works only because the character becomes inexplicably competent",
  "It works only because the character becomes inexplicably lucky",
  "It works only because a famous trope happens on cue",
  "It works only because the most boring object becomes the MVP",
  "It works only because a bystander does something wildly unhelpful first",
  "It works only because a rule is followed at the worst possible time",

  "It works only because the escape causes a different problem immediately",
  "It works only because someone presses a button without knowing what it does",
  "It works only because a safety feature activates in a nonsensical way",
  "It works only because a machine interprets the situation incorrectly",
  "It works only because an alarm triggers exactly the needed reaction",
  "It works only because the character is treated like they belong there",
  "It works only because someone mistakes the danger for a performance",
  "It works only because the escape happens in under three seconds",
  "It works only because the escape takes way too long but still succeeds",
  "It works only because the character survives with one ridiculous consequence"

];