window.DECKS = window.DECKS || {};
window.DECKS.setting = [

  "A fairy-tale stone bridge over a deep river at dawn",
  "A burning modern skyscraper stairwell with broken alarms",
  "A quiet suburban street during a neighborhood barbecue",
  "A serious sci-fi space station corridor with flickering lights",
  "A romantic lakeside pier at night with live music nearby",
  "A cartoon factory full of giant machines and slippery floors",
  "An ancient temple collapsing deep in the jungle",
  "A small-town diner just before closing time",
  "A luxury cruise ship deck during a violent storm",
  "A frozen arctic research base during a power outage",

  "A medieval battlefield moments after the fighting stops",
  "A children’s amusement park after hours, lights half on",
  "A crowded airport terminal during a sudden evacuation",
  "A haunted mansion hallway lit only by candlelight",
  "A high-speed train tunnel at full velocity",
  "A desert highway rest stop in extreme heat",
  "A secret underground laboratory with failing ventilation",
  "A pirate ship caught in a massive whirlpool",
  "A courtroom during a high-profile trial recess",
  "A volcanic island research camp as the ground trembles",

  "A floating sky city connected by narrow glass walkways",
  "A flooded underground parking garage",
  "A luxury hotel lobby during a blackout",
  "A deep-sea research submersible under crushing pressure",
  "A remote mountain cable car suspended over a ravine",
  "A fantasy kingdom throne room mid-coup",
  "A spaceport launch platform moments before liftoff",
  "A busy construction site with cranes overhead",
  "A quiet art museum during a late-night event",
  "A nuclear power plant control room during an anomaly",

  "A carnival midway as a storm rolls in",
  "A high-tech server farm overheating rapidly",
  "A crumbling cliffside monastery above the sea",
  "A subway platform as a train fails to stop",
  "A luxury yacht drifting without power",
  "A vast desert canyon during a flash flood",
  "A futuristic megacity street during a riot",
  "A remote lighthouse during hurricane winds",
  "An abandoned shopping mall echoing with alarms",
  "A snowbound mountain lodge cut off from the world",

  "A jungle rope bridge swaying in heavy rain",
  "A hospital emergency wing during system failure",
  "A city rooftop during a helicopter evacuation",
  "An underground fighting arena beneath a city",
  "A spacecraft cargo bay venting atmosphere",
  "A medieval castle tower struck by lightning",
  "A massive dam inspection platform mid-collapse",
  "A coastal town as a tsunami warning sounds",
  "A research greenhouse with runaway growth",
  "A remote observatory as the structure begins to fail"

];