window.DECKS = window.DECKS || {};
window.DECKS.setting = [

  "A fairy-tale stone bridge over a wide river at dawn",
  "A modern glass skyscraper interior just after sunrise",
  "A quiet suburban street during a weekend barbecue",
  "A serious sci-fi space station corridor during routine operations",
  "A romantic lakeside pier at night with distant music",
  "A brightly colored cartoon factory full of oversized machinery",
  "An ancient jungle temple covered in vines and carvings",
  "A small-town diner late in the evening",
  "A luxury cruise ship deck under a cloudy sky",
  "A frozen arctic research base at midday",

  "A medieval battlefield long after the fighting has ended",
  "A children’s amusement park after closing time",
  "A crowded international airport terminal",
  "A historic mansion hallway lit by chandeliers",
  "A high-speed train interior mid-journey",
  "A desert highway rest stop under a blazing sun",
  "A secret underground research facility",
  "A wooden pirate ship sailing open waters",
  "A courtroom during a short recess",
  "A volcanic island research camp",

  "A floating sky city connected by narrow walkways",
  "An underground parking garage beneath a city",
  "A luxury hotel lobby late at night",
  "A deep-sea research submersible on a scheduled dive",
  "A remote mountain cable car station",
  "A fantasy kingdom throne room",
  "A spaceport launch complex on a quiet day",
  "A busy urban construction site",
  "A quiet art museum after public hours",
  "A nuclear power plant control room",

  "A carnival midway in the early evening",
  "A high-tech server farm",
  "A cliffside monastery overlooking the sea",
  "A subway platform during normal service",
  "A luxury yacht drifting on calm waters",
  "A vast desert canyon under clear skies",
  "A futuristic megacity street",
  "A remote coastal lighthouse",
  "An abandoned shopping mall",
  "A snow-covered mountain lodge",

  "A jungle rope bridge spanning a ravine",
  "A hospital emergency wing",
  "A city rooftop overlooking downtown",
  "An underground fighting arena beneath a city",
  "A spacecraft cargo bay",
  "A medieval castle tower",
  "A massive hydroelectric dam",
  "A coastal town waterfront",
  "A research greenhouse full of experimental plants",
  "A remote mountain observatory under the stars"

];
