window.DECKS = window.DECKS || {};
window.DECKS.threat = [

  "Shot and falls into deep water",
  "Stabbed and locked in a freezer",
  "Thrown off a high bridge into rocks below",
  "Pinned under collapsing stone blocks",
  "Crushed by a massive industrial press",
  "Dragged toward spinning machinery",
  "Trapped in a room rapidly filling with smoke",
  "Locked in an elevator as the cables snap",
  "Caught in a stairwell as fire races upward",
  "Trapped behind a sealed door as oxygen runs out",

  "Hit by a vehicle and launched into oncoming traffic",
  "Electrocuted while standing in water",
  "Pulled into a fast-moving river current",
  "Caught in a flash flood inside a narrow canyon",
  "Buried alive under a sudden landslide",
  "Hanging from a ledge as the grip fails",
  "Falling through ice into freezing water",
  "Swept overboard during a violent storm",
  "Stranded in extreme heat without water",
  "Stranded in extreme cold without shelter",

  "Trapped in a sinking vehicle",
  "Trapped inside a flooding underground tunnel",
  "Caught in a building collapse with no clear exit",
  "Trapped in quicksand with weight pulling downward",
  "Chased into a dead end by armed attackers",
  "Cornered by a hostile crowd turning violent",
  "Held at gunpoint with a shaky trigger finger",
  "Poisoned and told the antidote is elsewhere",
  "Injected with something unknown and rapidly worsening",
  "Bleeding out with no medical help in sight",

  "Explosive decompression rips the air away",
  "Airlock cycles open while you’re halfway through",
  "Suit breach in vacuum with a spreading tear",
  "Sealed in a chamber as pressure increases",
  "Trapped in a capsule as it begins to vent",
  "Ejected from a vehicle at high speed",
  "Falling from a great height with nothing to grab",
  "A glass floor shatters beneath your feet",
  "A cable snaps and whips across the area",
  "A crane load drops directly above you",

  "A fuel leak ignites into a fireball nearby",
  "A gas line ruptures and the room fills fast",
  "A grenade rolls to your feet, pin already out",
  "A bomb timer hits the final seconds",
  "A door locks as alarms announce a purge",
  "You’re handcuffed as the floor begins to collapse",
  "You’re tied up as the waterline rises",
  "You’re trapped under rubble and the next collapse starts",
  "You’re trapped in a vehicle as it tips over the edge",
  "You’re forced onto a narrow walkway as it breaks apart"

];